Week_8_MKS/rails-devise-exercise/config/routes.rb
Metube::Application.routes.draw do
  devise_for :users
  root to: "videos#index"
  resources :sounds
  resources :videos

end

Week_8_MKS/rails-devise-exercise/app/models/sound.rb
class Sound < ActiveRecord::Base
  belongs_to :user
end

Week_8_MKS/rails-devise-exercise/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
end

Week_8_MKS/rails-devise-exercise/app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

Week_8_MKS/rails-devise-exercise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Week_8_MKS/rails-devise-exercise/app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  def index
    @sounds = Sound.all
  end

  def show
    @sound = Sound.find(params[:id])
  end

  def new
    @sounds = Sound.new
  end

  def create
    sound = Sound.new(sound_params)
    sound.save
    redirect_to root_path
  end

  def edit
    @sound = Sound.find(params[:id])
  end

  def update
    @sound = Sound.find(params[:id])
    @sound.update(video_params)
    redirect_to root_path
  end

  def destroy
    sound = Sound.find(params[:id])
    sound.destroy
    redirect_to root_path
  end

  private

  def sound_params
    params.require(:sound).permit(:title, :soundcloud_url)
  end
end

Week_8_MKS/rails-devise-exercise/app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(:id)
  end
end

Week_8_MKS/rails-devise-exercise/app/controllers/videos_controller.rb
class VideosController < ApplicationController

   before_action :authenticate_user!, :except => :index

# update the index page to only show the current user's videos.
  def index
    # @videos = Video.all
    if current_user
    @videos = current_user.videos
    else
    @videos = []
   end
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

# now we need to attach a new video to its creator
# we do this in the controller, right before we save the new video. 
# current_user.id ensures that a user can only create a video for themselves
  def create
    video = Video.new(video_params)
    video.user_id = current_user.id
    video.save
    redirect_to root_path
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    redirect_to root_path
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to root_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :description, :youtube_id)
  end
end

Week_8_MKS/rails-devise-exercise/app/helpers/application_helper.rb
module ApplicationHelper
end

Week_8_MKS/rails-devise-exercise/app/helpers/sounds_helper.rb
module SoundsHelper
end

Week_8_MKS/rails-devise-exercise/app/helpers/user_helper.rb
module UserHelper
end

Week_8_MKS/rails-devise-exercise/app/helpers/video_helper.rb
module VideoHelper
end

Week_8_MKS/rails-devise-exercise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Welcome to VideoCloset! You are signed in as <%= current_user.email %>.
  <%= link_to 'sign out', destroy_user_session_path, :method => :delete %>
<% else %>
  Please <%= link_to 'sign in', new_user_session_path %> first.
<% end %>

<%= yield %>

</body>
</html>

Week_8_MKS/rails-devise-exercise/app/views/sounds/index.html.erb
<h2>All Sounds:</h2>
<ul>
<% @sounds.each do |sound| %>
<li><%= link_to sound.title, "/sounds/#{sound.id}" %></li>
<% end %>
</ul>

Week_8_MKS/rails-devise-exercise/app/views/sounds/new.html.erb
<form action="/sounds" method="post">
  <label for="title">Title:</label>
  <input type="text" id="title" name="sound[title]">

  <label for="soundcloud_url">SoundCloud URL:</label>
  <input type="text" id="soundcloud_url" name="sound[soundcloud_url]">

  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <input type="submit" value="submit">
</form>

Week_8_MKS/rails-devise-exercise/app/views/video/index.html.erb
<h1>Video#index</h1>
<p>Find me in app/views/video/index.html.erb</p>

Week_8_MKS/rails-devise-exercise/app/views/videos/edit.html.erb
<form action=<%= "/videos/#{params[:id]}" %> method="post">
  <!-- This is needed because the browser does not support PUT in a form -->
  <!-- However, if Rails sees this input, it will treat it as a PUT request -->
  <!-- (this is normally generated by the built-in form_tag helper method) -->
  <input name="_method" type="hidden" value="put">

  <label for="title">Title:</label>
  <input type="text" id="title" name="video[title]">

  <label for="description">Description:</label>
  <input type="text" id="description" name="video[description]">

  <label for="youtube_id">Youtube ID:</label>
  <input type="text" id="youtube_id" name="video[youtube_id]">

  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <input type="submit" value="submit">
</form>

Week_8_MKS/rails-devise-exercise/app/views/videos/index.html.erb
<h2>All Videos:</h2>
<ul>
<% @videos.each do |video| %>
<li><%= link_to video.title, "/videos/#{video.id}" %></li>
<% end %>
</ul>

<%= link_to 'New Video', new_video_path %>

Week_8_MKS/rails-devise-exercise/app/views/videos/new.html.erb
<form action="/videos" method="post">
  <label for="title">Title:</label>
  <input type="text" id="title" name="video[title]">

  <label for="description">Description:</label>
  <input type="text" id="description" name="video[description]">

  <label for="youtube_id">Youtube ID:</label>
  <input type="text" id="youtube_id" name="video[youtube_id]">

  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <input type="submit" value="submit">
</form>

Week_8_MKS/rails-devise-exercise/app/views/videos/show.html.erb
<h1><%= @video.title %></h1>

<h3><%= @video.description %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video.youtube_id %>" frameborder="0" allowfullscreen></iframe>